name: Build MAUI Android (APK) — f_gaby

on:
  push:
    branches: [ f_gaby ]
    paths:
      - 'App.sln'                           # dispara si cambia la solución
      - 'App/**'                             # dispara si cambia cualquier archivo del proyecto
      - '.github/workflows/build-android.yml'
  workflow_dispatch:

env:
  SOLUTION: App.sln
  PROJECT: App/App.csproj                   # <- si tu .csproj se llama distinto, cámbialo aquí
  TF: net9.0-android                        # <- cambia a net8.0-android si tu proyecto usa .NET 8

jobs:
  build-android:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'           # cambia a 8.0.x si usas net8

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.sln', '**/*.csproj', '**/nuget.config') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Instalar workload MAUI (Android)
        run: dotnet workload install maui-android

      - name: Instalar Android SDK (cmdline-tools + plataformas)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $env:ANDROID_HOME = "$env:USERPROFILE\android-sdk"

          New-Item -ItemType Directory -Force -Path "$env:ANDROID_HOME\cmdline-tools\latest" | Out-Null
          Invoke-WebRequest -Uri https://dl.google.com/android/repository/commandlinetools-win-11076708_latest.zip -OutFile cmd.zip
          Expand-Archive cmd.zip -DestinationPath "$env:ANDROID_HOME\cmdline-tools\latest" -Force
          Remove-Item cmd.zip

          $SdkMgr = "$env:ANDROID_HOME\cmdline-tools\latest\bin\sdkmanager.bat"

          # Aceptar licencias (enviar muchas 'y' por la tubería)
          $accept = ("y`r`n" * 200)
          $accept | & $SdkMgr --licenses | Write-Output

          # Instalar componentes necesarios
          & $SdkMgr "platform-tools" "platforms;android-35" "build-tools;35.0.0"


      - name: Restore (solution)
        run: dotnet restore "${{ env.SOLUTION }}"

      - name: Publicar APK
        run: dotnet publish "${{ env.PROJECT }}" -c Release -f ${{ env.TF }} -p:AndroidPackageFormat=apk -o out

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-f_gaby
          path: out
